name: Parse JSON Example

on:
  workflow_dispatch:
    inputs:
      environmentProperties:
        description: 'JSON string (e.g. {"type":"R&D ecosystem"})'
        required: true
        type: string

jobs:
  parse-json:
    runs-on: ubuntu-latest
    steps:
      - name: Show raw input
        run: echo " \${{ inputs.environmentProperties }}"

      - uses: actions/github-script@v6
        id: parse-json
        with:
          script: |
            const envProps = JSON.parse(core.getInput('environmentProperties'));
            core.setOutput('type', envProps.type);
        env:
          environmentProperties: ${{ inputs.environmentProperties }}

      - name: Show extracted output
        run: echo " ${{ steps.parse-json.outputs.aep_type }}"
